### ISSUE TITLE
caching nix builds

### ISSUE THREAD

**Issue by KiaraGrouwstra** [sodiboo/niri-flake#7] opened 2024-02-14 16:02 UTC
i wonder if we could maybe alleviate local builds by say having a cachix user for niri.
if so, would it be best if this were done from niri-flake, from the upstream niri repo, or from both?

**Comment by sodiboo** [comment] 2024-02-15 07:11
I have considered this already, and i've talked briefly about it in the matrix chat room. I like the idea, but i think it'd have to be in upstream niri, for two different reasons:

(A) Trust. if i'm hosting the cached builds, then that inherently puts a level of trust on me for the users, that doesn't need to exist now. As of now, it's fairly easy to verify that the code really does compile the code in `YaLTeR/niri`, even without significant nix experience. It's also not too hard to keep up with most changes, as this is generally not updated that frequently and even then, not anything that's hard to grasp, usually "update deps", "fix build inputs after a new niri commit", "update README", and the occasional "actually refactor flake to implement something new". With a binary cache, this is no longer the case, as from my understanding, i can "just" upload malware and sign it. I wouldn't do something like that, but i am vaguely uncomfortable with the thought of "just trust me bro".

(B) Update frequency. It's possible to automate cachix builds with GitHub Actions and publish on every commit. This is ideal. This flake does *not* update with every commit of niri. I suppose it's more reasonable to cache, now that there are "stable" release tags. We could just cache the stable releases - not every commit. Though, if i were to cache every commit, the only reasonable way to do that is to have a scheduled task that automatically updates the `niri-src` input.

(C) what about nixpkgs? With the recently implemented fix for the driver issue, `niri-flake` no longer uses the same `nixpkgs` on all systems by default - instead, it's overriden by the config to use the system's `pkgs` special args. So what do we actually cache? the `packages.*.niri` output of the flake is not what most people will actually be building anymore. Realistically, even if we only support stable niri, i *do* expect unstable nixos to work no matter what (because.. that's the channel i'm running, so i think it's fair that i decide it must be supported in my own project - this same logic applies to `niri-src`). Therefore, we would pretty much need to schedule updates and at the same time update `niri-src` and `nixpkgs`. But do we support stable niri also? Stable nix? Then, we basically have a two-by-two matrix of supported versions, where if any of the four tracked sources (stable/unstable, niri/nixpkgs) have a new commit or release, then we cache two new builds (or four, if you multiply by the amount of build platforms). If this were implemented, that would honestly be perfect, besides potentially cluttering the commit history (but who cares, that can be filtered, or *can* be moved to a separate repo if too much of an issue)

The main reason i'm hesitant to even begin would be (A). If we could get upstream niri to cache nix builds (they use a different rust-nix toolchain, but that's okay as i use crate2nix primarily for the build times, given the lack of a cache), this would solve both (A) and (B) in one go, as well as make the CI cleaner (on every commit is possible when in same repo, instead of needing to schedule). It would also prevent the need for any kind of scheduled updates. It would make (C) worse, as it would not receive as frequent love and care as a dedicated nix repo would. (though, we *could* try to make it work anyways, and in general, stable nix is not *as* important of a target)

The main reason i actually don't do it would be (D) i don't know how to use cachix. I need to learn somehow, but it feels "wrong" to binary cache someone else's project when i am neither your distribution packager, nor a long-term contributor to the original project. I was gonna say i'm not a frequent contributor, but then again, i suppose i am. Not always in source code, but i've helped improve documentation, and significantly helped in making it work well on NixOS. So, really, the other reasons are not at all reason why we *can't* have a binary cache - they're reasons for me to procrastinate :3

Do you have any experience in using cachix? if you or someone else interested does, i'd love to have some guidance on how to do it and set up a cache. I suppose, a decent enough solution to (A) would be to just have a disclaimer that you are putting additional trust in me as a distributor. Writing this comment has made me realize how beautiful the setup can look, and i am suddenly motivated than i was before.

**Comment by sodiboo** [comment] 2024-02-15 07:28
> (A) Trust. if i'm hosting the cached builds, then that inherently puts a level of trust on me (...) i am vaguely uncomfortable with the thought of "just trust me bro".

> If we could get upstream niri to cache nix builds (...), this would solve both (A) and (B) in one go, as well as make the CI cleaner (on every commit is possible when in same repo, instead of needing to schedule). It would make (C) worse, as it would not receive as frequent love and care as a dedicated nix repo would. Of course, that's just a result of the current state of nix already in YaLTeR/niri, not something we couldn't solve. Even with the current state of nix in YaLTeR/niri, we could just make sure it has nixpkgs unstable updated frequently and leave stable nix alone.

@YaLTeR thoughts? Ultimately, a binary cache is opt-in by design. Existing users cannot and will not download anything from a binary cache without explicitly adding it as a trusted signing authority (at least, that's my understanding). Would you be okay with me implementing this? Would you prefer to it be implemented in upstream niri? At that point, i think it would be reasonable to move the whole module into upstream niri as well, and deprecate this repo. But then, how would we handle stable niri? It needs to be kept up-to-date with updates to nixpkgs (or mesa will eventually become outdated).

**Comment by YaLTeR** [comment] 2024-02-15 08:24
> Would you be okay with me implementing this?

Sure. I mean, almost nobody reads AUR PKGBUILD for example, so this trust issue is already implied in most packages.

> Would you prefer to it be implemented in upstream niri?

I'd prefer it to be separate, I think it's better to keep nix concerns to a separate nix repo, they can be addressed quickly and without dragging away focus in the main repo issues. Also it's not like *every single commit* needs to update the cache. If it happens once a day or once a week or just for stable releases, that sounds reasonable to me.

**Comment by sodiboo** [comment] 2024-02-15 13:18
> Sure.

Alright, awesome! Let's do some caching!

> I mean, almost nobody reads AUR PKGBUILD for example, so this trust issue is already implied in most packages.

From my understanding, AUR packages are compiled locally (of course, not including ones with binary blobs but that's not part of what I'm talking about, and inevitable for proprietary software). This is akin to my current package, which is also compiled locally. True, many people won't read it still.

Though, from my personal experience, I think the percentage of those who do on nix is higher because to use NixOS, you must be able to work with the Nix language, which is used for packaging too. I regularly read the source of nix packages I'm using, even ones in nixpkgs. Say what you will about what that means for how robust the systems are ("a good technology is one you don't have to think about when using. given that, i sure do think about Bluetooth a lot"), but I *do* read them often. compare that to Arch, which I have used previously, and I never read any PKGBUILD, nor learned to make one. I didn't need to at the time. I can read the niri PKGBUILD, and I did just now but having never looked at one before, though it was slightly overwhelming and ultimately it just does like... cargo build and copies files. But it looks like it does so much more at that length. It also remaps the path prefix so that the arch-specific build does aren't exposed in traces (which I do too).

No matter how many do actually read the source of the package they install, that's missing my point completely. Binary distribution *needs* trust by being inherently opaque, which is different than the current state of niri packaging which does not *need* trust, it is transparent and the people who don't read the packaging source are doing it out of convenience. With a binary cache, your only option to establish trust is to actually compile it locally and compare results, which defeats the point of a binary cache.

Personally, I think the total size of source code is more relevant to whether it is reasonable to read. I haven't read the full niri source code, it's not reasonable for me to do, so I am putting trust in you by doing that. It is reasonable to read a <100 line PKGBUILD or <300 line nix package + modules, therefore there is no "absolute trust out of laziness", at least for me.

Therefore, my logic goes, it is best if [The Software That I'm Too Lazy To Audit The Source Code Of]'s author is the one signing/managing the binary cache (since they are already trusted to run unreviewed code on my machine, so what difference does it make if it is unreviewable?)

> Also it's not like every single commit needs to update the cache. If it happens once a day or once a week or just for stable releases, that sounds reasonable to me.

Personally, given that I myself use the latest commit on my system, I *do* think every commit should update the cache as soon as possible. If anything, that's more important than keeping the stable releases cached, because they are more frequent (and thus, users will experience more frequent rebuilds = more wasted time per capita for unstable than on stable).

nixpkgs is less frequent, especially for updates that affect niri, so running that daily would be just okay. there is a risk that the nixpkgs update hasn't made it into the binary cache yet, and if this were in upstream niri without also moving all of nix there (i.e. module is still managed here), that might actually break the user's system if niri is not updated (given that we don't implement our own unstable cross-repo-dependent nix interfaces to solve the mesa issue that way). With how it's currently set up in this repo, the worst fate possible is a forced rebuild.

**Comment by KiaraGrouwstra** [comment] 2024-02-16 02:41
on nixpkgs version, i run unstable too. that said, i would rather give up the like 50 mb of storage to also keep a copy of stable nixpkgs if that were to mean not having to spend time rebuilding niri on each update.
not that cached unstable wouldn't be cool, tho skipping that for now might be easier than keeping it updated too. tho, i guess it should be possible to automate that too.

on using cachix, i think their docs def help. ^^

the trust concerns reminded me a bit of [this thread](https://discourse.nixos.org/t/git-verify-in-band-commit-verification/38991) i saw come by today, tho i'm not sure that helps for cachix.

**Comment by sodiboo** [comment] 2024-02-16 06:49
>  i would rather give up the like 50 mb of storage to also keep a copy of stable nixpkgs if that were to mean not having to spend time rebuilding niri on each update

Though, this is not the whole story. `mesa` must match. So you're not just "keeping a copy", you're running that as your main. Is it possible to manually override mesa? I'd imagine it is, but surely other packages might break then?

> on using cachix, i think their docs def help. ^^

Oh yeah, i have read some of them. I've just not been "invested" in doing it (see above notes on procrastination), and my naive impression is that it's not entirely clear how the process works or how to set it up for my use case.

> the trust concerns reminded me a bit of [this thread](https://discourse.nixos.org/t/git-verify-in-band-commit-verification/38991) i saw come by today, tho i'm not sure that helps for cachix.

This seems to be about signing git commits to eliminate trust of the remote repository vendor. For nixpkgs, this is reasonable, their builder automatically fetches from GitHub and builds and signs it autonomously. I don't know why, but i have an inherent trust in these autonomous systems. That's not for a rational reason, just that it "feels" more trustworthy because i'd imagine no one single person can easily sign anything not going through nixpkgs. If cachix were just "Hydra but you can add your own repo and we'll do the rest", i.e. "point us to your flake, we'll build and cache and serve it" i would trust it more, because the individual developer does not have control over the actual binary, just the build process which is published and followed by a bot. Like F-Droid, which also builds all applications on-site from source, and does not allow binary uploads. This system still requires trust, but in a single system with an established userbase. With cachix, i alone (and whoever i share it with, intentionally or not) hold the signing keys. From my understanding, it's essentially just file storage targeted at nix users. I'm responsible for building, uploading, and signing binaries. That's an important distinction, because now, when using this, you are trusting the one single individual. I'm not scared of any actual risk of compromise - i'm confident that i will never serve you malware, but i don't expect you to take that at face value and inherently trust it. If a trusted third party built them automatically (such as nixpkgs' hydra infrastructure), then *they're* the one you're inherently trusting, not me (because everything i publish is then easily audited).

As you might be able to tell by the length of my replies on the topic, i have a lot of feelings about it. It's not too different from password storage - it is inherently a sensitive task, that can have consequences if i don't do it properly. I would *much* prefer it be outsourced to a third party, like if there was an "Upload nix expressions and we'll handle the rest" service, that people already trusted, or in the analogy to password storage, simply not letting you use email/password with my service, and rather only have login with GitHub.

Ultimately, i think i made my mind up in the previous comment. I'll just bite the bullet and actually try to do it.

---

Also, nixpkgs niri just got merged! We're not going to cache stable niri in this repo, as soon enough it will already be part of nixpkgs (and!! we get to completely ignore the mesa issue for stable niri because it will build with the rest of nixpkgs) This repo will then provide modules and bleeding edge packages.

**Comment by KiaraGrouwstra** [comment] 2024-02-16 14:56
right, i see your point about hydra-like systems being nicer.

especially with niri having been merged to nixpkgs, that would maybe raise the question if using this module with their niri package as well. while i've been pretty excited for new niri features, i'll admit if this repo can focus on nix-y stuff over caching every permutation that'd seem nice as well.

**Comment by sodiboo** [comment] 2024-02-22 14:26
I've created a binary cache at `niri.cachix.org` and the first build succeeded in 16 minutes (https://github.com/sodiboo/niri-flake/actions/runs/8005765016/job/21865962010). I'd hope that subsequent builds are gonna go a little faster, having already cached many dependencies. I think you can add the public key to your nix config, and it'll work automatically.

**Comment by sodiboo** [comment] 2024-02-22 21:43
The problem is that the builds uploaded by GitHub Actions have a different hash from the one my system wants to build locally. Cachix docs suggest downloading the cached version, and running `nix-diff`, which is all good and well except for the fact that the cache doesn't seem to contain the actual derivations for niri, only the built results. As such, i cannot download the derivation, which is needed for cache to work. I get this error if i try to diff the cached and local builds:

```
> nix-diff /nix/store/cn5czczhpyv9ncfmvcnw8qm1xqsigbhi-rust_niri-0.1.2 $(nix eval --raw .#niri-stable)
nix-diff: /nix/store/msp3m83zm2zx6xy034fd3z3c7f4c3zl5-rust_niri-0.1.2.drv: withBinaryFile: does not exist (No such file or directory)
```

`/nix/store/cn5czczhpyv9ncfmvcnw8qm1xqsigbhi-rust_niri-0.1.2` is the result of `nix build .#niri-stable` from GitHub Actions. It has been stable for all 3 runs, across different commits, so clearly there is *something* reproducible about `niri-flake` that works in CI but is not consistent to my machine (niri-unstable package was not as stable in output, due to accidentally relying on stable tag for resources). You can download the result from the cache if you search for it https://app.cachix.org/cache/niri#search
`/nix/store/msp3m83zm2zx6xy034fd3z3c7f4c3zl5-rust_niri-0.1.2.drv`, however, is the deriver of that path. It does not get downloaded when you realize the path. Cachix search does not list it in the results. Documentation does not seem to have an easy way to ensure derivations are uploaded. anti-patterns/best-practices documentation also does not seem to contain anything that i'm obviously doing incorrectly that would cause nonreproducible builds. Cachix doesn't seem to actually host the derivation file anywhere, which is obviously inconvenient if i want to debug it.

@KiaraGrouwstra Do you have any idea what might cause this?

`nix eval --raw .#niri-stable` on my system, for reference, outputs `/nix/store/lwb2finnfgm67hv6n8wayxczivyg8fx5-rust_niri-0.1.2`. Is it the same on yours, or different yet again?

**Comment by sodiboo** [comment] 2024-02-22 21:56
One possible source for the nonreproducibility that i find, might be different versions of nix? That doesn't feel like it would follow nix philosophy, if everything changes upon upgrading nix (it is not a dependency of the application), but CI gets 2.19.2 https://github.com/sodiboo/niri-flake/actions/runs/8011204611/job/21883900099#step:3:349 whereas on my system `nix --version` => `nix (Nix) 2.18.1` which is the default version of just plain `nix` package on nixpkgs unstable (which seems to be equal to "nix stable"? i.e. the actual tooling, not nixpkgs)

**Comment by sodiboo** [comment] 2024-02-22 21:57
> Do you have any idea what might cause this?

Also, do you have any idea how i might obtain the derivation produced in CI, such that i can diff it with local?

**Comment by KiaraGrouwstra** [comment] 2024-02-22 22:32
looks like [you can](https://github.com/cachix/cachix/issues/9) upload the actual derivations to cachix as well.

matching nix versions could help, but maybe the derivations can help give more info there...

i get the same nix-stable hash as you :), also on unstable nixpkgs.

**Comment by sodiboo** [comment] 2024-02-22 23:23
> looks like you can upload the actual derivations to cachix as well.

Seems to work. It's pushing a lot of new paths now: https://github.com/sodiboo/niri-flake/actions/runs/8012279567/job/21887240754

**Comment by sodiboo** [comment] 2024-02-22 23:49
Heck yeah! I can download the derivation now.

```
- /nix/store/cn5czczhpyv9ncfmvcnw8qm1xqsigbhi-rust_niri-0.1.2:{out}
+ /nix/store/lwb2finnfgm67hv6n8wayxczivyg8fx5-rust_niri-0.1.2:{out}
• The input source named `source` differs
• The input derivation named `rust_niri-config-0.1.2` differs
  - /nix/store/hsa1c1c0vc2v0c9dxijsiy1ism0q1hll-rust_niri-config-0.1.2.drv:{lib}
  + /nix/store/qzqrj97vzwn831sg3vkr5f6w1l385hd4-rust_niri-config-0.1.2.drv:{lib}
  • The input source named `source` differs
  • The input derivation named `rust_niri-ipc-0.1.2` differs
    - /nix/store/p9slkmdi2cw9jmq6alihk38s30k0kh1d-rust_niri-ipc-0.1.2.drv:{lib}
    + /nix/store/d5h2sg0a219svyiissb9j52bivhzw22n-rust_niri-ipc-0.1.2.drv:{lib}
    • The input source named `source` differs
    • The environments do not match:
        src=''
        [[- /nix/store/0csnfshpwrxiblshry6yajc6czdmhhsy-source ]][+ /nix/store/nl0vqmprmxky4jpvap4ymwjm4a7glskh-source ]]
    ''
  • Skipping environment comparison
• The input derivation named `rust_niri-ipc-0.1.2` differs
  • These two derivations have already been compared
• Skipping environment comparison
```

with my own flavoring of `[[+ inline-addition ]]` and `[[- inline-removal ]]` to replace red/green bg color

**Comment by sodiboo** [comment] 2024-02-22 23:52
It is also important to note, that the two paths above appear to be identical except for their actual, well, path. diffing the contents returns absolutely no changes whatsoever. they reference the `niri-ipc` subdirectory of `YaLTeR/niri`

**Comment by KiaraGrouwstra** [comment] 2024-02-23 00:21
so the diffs seem to manifest only at the build results yet not at the derivation?
that does seem odd. might this be about nix versions then?

**Comment by sodiboo** [comment] 2024-02-23 00:36
It seems to be that, despite having identical contents, the hashes of the sources generated by crate2nix are different. I think this is likely a symptom of import-from-derivation. However, fear not! The solution appears quite simple. Just override the `src` argument for each crate. I've done it on a separate branch, just so i can keep it separate from main for now: https://github.com/sodiboo/niri-flake/compare/main...cache_experiments

**Comment by sodiboo** [comment] 2024-02-23 00:39
Update: The Ci job finished, and my system can now substitute from the binary cache! Yay! Time to implement into main.

**Comment by sodiboo** [comment] 2024-02-23 00:48
Binary cache is now implemented, and it's reproducible: https://github.com/sodiboo/niri-flake/commit/9dc8b646ffdbe5316b7d8df5152243ce0a90ae34

This issue is *not* complete, however. Before we finish up, there are a couple more things to do:
- Document the binary caching, and how to enable it.
- Set up automation to create PRs soon after pushes to niri. (and updates to nixos-unstable, for that matter)
- Set up automation to merge those PRs once the builds are finishes, if the builds are successful

**Comment by sodiboo** [comment] 2024-02-23 15:19
- [X] Document the binary caching, and how to enable it.
- [X] Set up automation to create PRs soon after pushes to niri. (and updates to nixos-unstable, for that matter)
- [ ] Set up automation to merge those PRs once the builds are finished, if the builds are successful

**Comment by sodiboo** [comment] 2024-02-24 04:28
CI now runs on PRs and it works well. Here are the three pull-requests that automation made thus far:

- #8
- #9
- #10

**Comment by sodiboo** [comment] 2024-02-24 04:31
Basically everything i need now is implemented, except for one final piece: Automatically merge PRs made by `github-actions[bot]` if and when all checks have passed.

**Comment by sodiboo** [comment] 2024-02-24 04:34
> Here are the three pull-requests that automation made thus far

See also: frustrating commit history. https://github.com/sodiboo/niri-flake/compare/354995b9621922eda5491f892441740781660869...ca963fe6334bb075c560e58121683ae919170083

**Comment by KiaraGrouwstra** [comment] 2024-02-24 10:32
that feels a bunch like what my commit history tends to look like 😄🙈

**Comment by sodiboo** [comment] 2024-02-24 15:15
I've added `mergify` to this repo, and set up rules to match. https://github.com/sodiboo/niri-flake/commit/eaf1968f0fb4b2cd6f524416f13be0140b16ba8b

Their online editor has a playground to check whether it will trigger on specific pull requests, and the only thing that seems off is the fact that none of the currently existing PRs will merge, because the `-closed` merge requirement is not met. I suspect this simply means that the PR is *already closed*, therefore mergify will not act on it. If that's the case, then based on their config checker the rules should be correct.

**Comment by sodiboo** [comment] 2024-02-24 15:41
I'm updating my warnings to reflect the fact that the `niri-src` input is deprecated, and i'm noticing like basically everything i wrote about nixpkgs niri doesn't apply anymore. Now, with binary caching, there is approximately zero benefit to making that one the default. I'm gonna make my own `niri-stable` the default again, even though i've written in many places that `nixpkgs` will be the default.

**Comment by KiaraGrouwstra** [comment] 2024-02-24 16:43
that's cool! i don't really want nixpkgs to get in the way of niri features myself, so i'd def welcome that.
i'm a bit confused still on how one would use unstable now (aside from using the now-deprecated `niri-src`), so looking forward to a readme update on that.

> Scary!

that was how i felt when trying to `nixos-rebuild` to your config earlier 🙈, i'd never tried something like that before

**Comment by sodiboo** [comment] 2024-02-24 16:45
#12 was just created, pushed, built, and merged completely autonomously. I think it's safe to say that the binary cache is now complete, including automatic updates.

**Comment by sodiboo** [comment] 2024-02-24 16:48
> i'm a bit confused still on how one would use unstable now (aside from using the now-deprecated `niri-src`), so looking forward to a readme update on that.

Does the commit i pushed while you were writing this sufficiently answer the concern?

https://github.com/sodiboo/niri-flake/commit/5626d865a42ce58aa0e90f4824441323ca720fff

**Comment by sodiboo** [comment] 2024-02-24 16:55
If you do not wish to use an overlay, you can also just use `niri.packagess.x86_64-linux.niri-unstable` directly. The difference is that this will use `nixpkgs` from latest commit to flake, but overlay `pkgs.niri-unstable` is guaranteed to match your system's nixpkgs. In 99% of cases, this will match, but after nixpkgs updates there may be a slight window where it isn't. In that timeframe, using the overlay makes you rebuild niri, which is slightly more preferable than the worst-case scenario for out-of-sync, where mesa will be out of sync.

**Comment by sodiboo** [comment] 2024-02-24 17:35
I'm gonna take the heart reaction as my response being a sufficient answer to your question about using niri-unstable. I consider a binary cache to be successfully implemented. This issue can now be closed

**Closed by sodiboo** 2024-02-24 17:35 UTC

**Comment by KiaraGrouwstra** [comment] 2024-02-24 17:55
thanks, that seems clear.
i am however [having issues](https://codeberg.org/kiara/cfg/commit/5d0cd89d25a51d6327ae6e9f08f22f4421c5098a#diff-58cb4f58166586c1ed7f076c568d41682df3661c) running that still tho:

> error: attribute 'niri' missing
> inputs.niri-flake.overlays.niri
> ^

would you have a working commit on this on your repo? i'm curious what i'm getting wrong there

**Comment by sodiboo** [comment] 2024-02-24 18:32
> thanks, that seems clear. i am however [having issues](https://codeberg.org/kiara/cfg/commit/5d0cd89d25a51d6327ae6e9f08f22f4421c5098a#diff-58cb4f58166586c1ed7f076c568d41682df3661c) running that still tho:
> 
> > error: attribute 'niri' missing
> > inputs.niri-flake.overlays.niri
> > ^
> 
> would you have a working commit on this on your repo? i'm curious what i'm getting wrong there

The commit you've linked seems to lock `niri-flake` to an older revision: https://codeberg.org/kiara/cfg/src/commit/5d0cd89d25a51d6327ae6e9f08f22f4421c5098a/flake.nix#L94

The overlay was added 5 commits later: https://github.com/sodiboo/niri-flake/compare/8eb71d53594db49935b6d1fa50c5e7b44d3ae567...251aca19f7f10b71dd81b11af012393ffa5b15bd

I recommend unpinning the niri-flake revision.

The latest revision of my own config builds just fine for me, and uses the overlay like so (verbatim equal to the README): https://github.com/sodiboo/nix-config/blob/6457cb8528a066088eed800224e347f088deb199/niri.mod.nix#L156-L157

**Comment by KiaraGrouwstra** [comment] 2024-02-24 19:06
ah whoops, thanks! :pray:
