### ISSUE TITLE
xwayland-satellite evaluation warning

### ISSUE THREAD

**Issue by hatosu** [sodiboo/niri-flake#533] opened 2024-10-04 18:49 UTC
"trace: evaluation warning: `pkgs.xwayland-satellite` will change behaviour in the future"

what do i specifically have to set in order to fix this? i apologize for making an issue here asking for help but, i have zero clue on how to get rid of this as setting "xwayland-satellite-unstable" in my environment packages list does not work :(

**Comment by sodiboo** [comment] 2024-10-05 19:52
> "trace: evaluation warning: `pkgs.xwayland-satellite` will change behaviour in the future"

note that the evaluation warning spans several lines

> trace: evaluation warning: `pkgs.xwayland-satellite` will change behaviour in the future.
> 
> Previously, `pkgs.xwayland-satellite` was provided by this flake.
> However, this (naively) overrides the version provided by nixpkgs.
> Now, xwayland-satellite gets similar treatment to niri.
> If you want to use the version you were previously using, use `pkgs.xwayland-satellite-unstable`.
> 
> For now, this is a warning and the behaviour is unchanged.
> This invocation still uses the unstable version provided by this flake.
> 
> You can use the nixpkgs version explicitly by using `pkgs.xwayland-satellite-nixpkgs`.
> That version will at a future point have a warning to switch back to `pkgs.xwayland-satellite` when that alias is removed from the overlay.

---

but, i also notice you were having further troubles:

> setting "xwayland-satellite-unstable" in my environment packages list does not work :(

this is very strange. that is the way to fix the warning. somewhere in your system closure, `pkgs.xwayland-satellite` is still referenced. try searching across your whole config (likely `Ctrl+Shift+F` in many editors) for `xwayland-satellite`, see if it pops up in several locations of your config. maybe you're accidentally putting it in system *and* home packages?

**Comment by sodiboo** [comment] 2024-10-31 12:46
closing this, since you never responded and it's also not really an issue to begin with; this warning was intended, and it's no longer emitted.

**Closed by sodiboo** 2024-10-31 12:46 UTC
